on:    
  workflow_dispatch:

name: update-sinan

jobs:
  
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create JSON
        shell: bash
        env:
          GCP_AUTH: ${{ secrets.GCP_AUTH }}
          GCP_AUTH_OPENSUS_DEV: ${{ secrets.GCP_AUTH_OPENSUS_DEV }}
        run: |
            echo $GCP_AUTH_OPENSUS_DEV > gcp-auth-dev.json
            ls -l
            
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Install Curl
        run: sudo apt-get install libcurl4-openssl-dev
        
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: | 
            googleCloudStorageR, RCurl, stringr, tidyr, arrow, fs, read.dbc
            
      - name: Update SINAN  - BOTU
        run: |
          source("code/download_upload_sinan.R")
          download_upload_sinan("BOTU")
        shell: Rscript {0} 

      - name: Update SINAN - COLE
        run: |
            source("code/download_upload_sinan.R")
            download_upload_sinan("COLE")
        shell: Rscript {0} 
        
      - name: Update SINAN - TUBE
        run: |
            source("code/download_upload_sinan.R")
            download_upload_sinan("TUBE")
        shell: Rscript {0} 